#!/bin/bash
set -e
trap "exit" INT

# compile flood
make clean
make
sudo make install

# reset leveldb directory
if [ "$1" == "reset" ]; then
    rm -Rf links
    if [ "$HOSTNAME" != "loopy" ]; then
        ./parse -f data/test2.xml-clean
    fi
fi
